import Head from "next/head";
import Footer from "../components/Footer";
import Media from "../components/Media";
import { useCallback, useEffect, useState } from "react";
import {
  Page,
  Button,
  ColorPicker,
  Form,
  FormLayout,
  TextField,
} from "@shopify/polaris";

export default function Home() {
  const [value, setValue] = useState("Your Quote");
  const [color, setColor] = useState({
    hue: 300,
    brightness: 1,
    saturation: 0.7,
    alpha: 0.7,
  });

  const [mediasrc, setMediaSrc] = useState("/public/test.png");

  useEffect(() => {
    console.log(mediasrc);
  }, [mediasrc]);

  const handleSubmit = useCallback(
    async (_event) => {
      _event.preventDefault();
      if (!value || value.length > 100) return false;
      try {
        const response = await fetch("/api/submit", {
          method: "POST",
          body: JSON.stringify({ quote: value, color: color }),
        });
        const data = await response.json();
        console.log(data);
        if (data.status === "ok") {
          setMediaSrc(data.imagesrc);
        } else {
          alert("Something went wrong");
        }
      } catch (err) {
        console.log(err.message);
        alert("Something went wrong");
      }
    },
    [value, color]
  );

  const handleValueChange = useCallback((value) => {
    setValue(value);
  }, []);
  const handleColorChange = useCallback((color) => {
    setColor(color);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page title="Color Picker">
        <Form onSubmit={handleSubmit}>
          <FormLayout>
            <ColorPicker
              onChange={handleColorChange}
              color={color}
              allowAlpha
            />
            <TextField
              value={value}
              onChange={handleValueChange}
              label="Your Quote"
              type="text"
              autoComplete="off"
              placeholder="Your quote"
            />
          </FormLayout>
          <Button submit>Submit</Button>
        </Form>
        <br />
        <Media src={mediasrc} />
        <Footer />
      </Page>
    </>
  );
}
